### ISSUE TITLE
A couple improvements

### ISSUE THREAD

**Issue by dougsyer** [zenoss/zenoss-RM-api#22]
Would help if its easier to not automatically call the introspection router.  Also will help if its easier to pass in the config as any basic object so its less bound to the creds file.  That would make it easier to secure.

**Comment by nrdynmd** [comment]
What is the use-case (or cases) in which automatically calling the introspection router causes complexity or issues ?

"_That would make it easier to secure._" The credentials would still need to be 'stored' somewhere, even though they are being passed in to the object. If you were integrating with a password-store type system, to solve, would imagine one would just need to override the "_\_getConfigDetails_" method.

**Comment by dougsyer** [comment]
1. I have a few custom routers and use others from zenpacks not defined in the static list so Im trying to figure out a better way to manage that and have it not cause errors.

If i know what call im making in production then the second introspect call isnt necessary and just adds load.

If something goes wrong then i believe the error you get refrences the introspection router which is confusing at first.


2.  Creds do need to be somewhere and im not critical of the default implementation but in production they obviously cant be in a flat unencrypted file.  So im asking for an official supported hook to pass the config in. Ie if i can pass the config as a simple namespace object i can then pass it with arg/opt parse or pull creds and config from somewhere more secure like a pillar in salt

**Comment by amccurdy** [comment]
1. The static list is only in use by ZenAPIConnector; the new zenApiLib stuff makes an IntrospectionRouter call to resolve your router url and verify that the method you're trying to call is valid... so you can use whatever routers you want.

2. That's a good idea for sure. With Zenoss Cloud, we'll be moving to use api keys (a much more modern solution than local authentication) so I'm not sure how much time we'll be able to spend on that request. I'll keep it in mind, though.

**Comment by cdecc** [comment]
Is there any progress in using a secure authentication mechanism to use the api instead of sending usr/pwd in cleartext over the network?
We are 2020 after all ;-)

**Comment by zensaiello** [comment]
Zenoss ResourceManager communication is done over HTTPS. While HTTP BasicAuth is not a secure authentication method, when accessing an API endpoint via HTTP, the usr/pwd is not being sent 'cleartext over the network'.
