### ISSUE TITLE
timeouts /errors not being handled sometimes?

### ISSUE THREAD

**Issue by dougsyer** [zenoss/zenoss-RM-api#3]
I havent seen this issue before...i have been working alot with this helper library in the past week.  im not sure if its limited to this router or not but today when i started trying to call methods in the router i started getting what im assuming is maybe a unhandled timeout calling introspection router?

the calls are good, it works sometimes, other times it doesnt.

doing this:

mr = zenApiLib.zenConnector(routerName="MonitorRouter")
mr.callMethod('getCollector', collectorString='localhost')

It looks like maybe the tree/monitor router may respond slowly perhaps or sometimes it throws errors..  it works sometimes othertimes it throws an error like the method doesnt exist however it does exist because i get returns sometimes...

when it fails i see this:

   112                     method[0],
    113                     self._routerName,
--> 114                     sorted(self._routersInfo[self._routerName]['methods'].keys())
    115                 ))
    116         if self.log.getEffectiveLevel() == 10:

**Comment by nrdynmd** [comment]
Added configuration option for 'timeout' to the credential file. Previous behavior was that connection would never timeout and the call would possibly hang waiting on response.
