### ISSUE TITLE
zenApiLib -- creds.cfg

### ISSUE THREAD

**Issue by cdecc** [zenoss/zenoss-RM-api#34]
Is it possible to use also credsections with the zenApiLib as with zenApiCli?

I have different environments, and it would be nice to be able to specify this somewhere.

**Comment by nrdynmd** [comment]
Specifying which credential section to use is. You can find the use outlined in the README.md. Section **zenApiLib.py**, example _#3_

tr5 = zenApiLib.zenConnector(**section = '5x'**, routerName = 'TriggersRouter')
